### ISSUE TITLE
question regarding to exercise 2

### ISSUE THREAD

**Issue by shangsunset** [mafintosh/p2p-workshop#11]
Hi, thanks for this workshop. Its a very good resource for learning p2p!

Im kinda confused about the following code, could you explain a little?

``` javascript
clients.forEach(function (client) {
    socket.on('data', function (data) {
      client.write(data)
    })
    client.on('data', function (data) {
      socket.write(data)
    })
  })
```

It seems to me that `forEach` is not called when a message is sent from a client, but how are the two events triggered inside the `forEach`?
I had 3 clients connected to the server, the two events(`socket.on` and `client.on`) are triggered differently when a  message is sent from a different client. Why does it happen like this?
When is each event called when one of the clients sends a message? I guess im having a hard time differentiating `socket` and `client` here.

Thanks again.

**Comment by mafintosh** [comment]
@shangsunset sry i missed your question. did you figure it out or do you still need help?

**Comment by shangsunset** [comment]
Hey @mafintosh , yea I have better understanding how it works now. thanks!
